AWSTemplateFormatVersion: "2010-09-09"
Description: hello world lambda that deploys through riff-raff and gets credentials from s3

Parameters:
    App:
        Description: Application name
        Type: String
        Default: fulfilment-node-stub-lambda
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE

Resources:
    FulfilmentNodeStubLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub FulfilmentNodeStubLambda-${Stage}
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource: "*"
                - PolicyName: PrivateBucket
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action: s3:GetObject
                            Resource: arn:aws:s3:::fulfilment-private/*
    FulfilmentNodeStubLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: hello world lambda that deploys through riff-raff and gets credentials from s3
            FunctionName:
                !Sub fulfilment-node-stub-lambda-${Stage}
            Code:
                S3Bucket: fulfilment-node-stub-lambda-dist
                S3Key: !Sub membership/${Stage}/fulfilment-node-stub-lambda/fulfilment-node-stub-lambda.zip
            Handler: index.handler
            Role:
                Fn::GetAtt:
                - FulfilmentNodeStubLambdaRole
                - Arn
            MemorySize: 512
            Runtime: nodejs6.10
            Timeout: 300
        DependsOn:
        - FulfilmentNodeStubLambdaRole

    FulfilmentNodeStubLambdaAPIPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub fulfilment-node-stub-lambda-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: FulfilmentNodeStubLambda

    FulfilmentNodeStubLambdaAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: hello world lambda that deploys through riff-raff and gets credentials from s3
            Name: !Sub fulfilment-node-stub-lambda-api-${Stage}
