AWSTemplateFormatVersion: "2010-09-09"
Description: hello world lambda that deploys through riff-raff

Parameters:
    DistBucket:
        Description: The S3 Bucket for distributing code in this account
        Type: String
    App:
        Description: Application name
        Type: String
        Default: node-stub-lambda
    Stack:
        Description: Stack name for the account which will hold this lambda
        Type: String
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE

Resources:
    NodeStubLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub NodeStubLambda-${Stage}
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource: "*"
    NodeStubLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: hello world lambda that deploys through riff-raff
            FunctionName:
                !Sub node-stub-lambda-${Stage}
            Code:
                S3Bucket: !Sub ${DistBucket}
                S3Key: !Sub ${Stack}/${Stage}/node-stub-lambda/node-stub-lambda.zip
            Handler: index.handler
            Role:
                Fn::GetAtt:
                - NodeStubLambdaRole
                - Arn
            MemorySize: 512
            Runtime: nodejs6.10
            Timeout: 300
            Environment:
                Variables:
                    'Stage': !Sub ${Stage}
        DependsOn:
        - NodeStubLambdaRole
    NodeHelloLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: hello world lambda that deploys through riff-raff
            FunctionName:
                !Sub node-hello-lambda-${Stage}
            Code:
                S3Bucket: !Sub ${DistBucket}
                S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
            Handler: hello.handler
            Role:
                Fn::GetAtt:
                - NodeStubLambdaRole
                - Arn
            MemorySize: 512
            Runtime: nodejs10.15
            Timeout: 300
            Environment:
                Variables:
                    'Stage': !Sub ${Stage}
        DependsOn:
        - NodeStubLambdaRole

    NodeStubLambdaAPIPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub node-stub-lambda-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: NodeStubLambda

    NodeStubLambdaAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: hello world lambda that deploys through riff-raff
            Name: !Sub node-stub-lambda-api-${Stage}
